### ISSUE TITLE
Fix top layer contention by possibly moving to overlay layer

### ISSUE THREAD

**Issue by kRHYME7** [AndreasBackx/waycorner#19] opened 2023-11-18 12:40 UTC
Hello, I'm using waybar on hyprland is there a way to make waycorner on top of hyprland?  Thank you

**Comment by AndreasBackx** [comment] 2024-03-19 22:47
Apologies for not seeing this earlier. It should work on top of any wlroots compositor. Please let me know if the example doesn't work for you. I'll close this for now as this is a bit old, please reopen if you're having any issues and provide some context. :)

**Comment by kRHYME7** [comment] 2024-03-19 23:12
Thank you! Sorry for not elaborating more. 

My concerns at this time is if it is posible to make waycorner on top of everything. 

Example: 

launch waybar
launch waycorner
relaunch waybar 
waybar is on top of waycorner. 

```
❯ hyprctl layers
Monitor eDP-1:
	Layer level 0 (background):
		Layer 56c8bde597e0: xywh: 0 0 1500 1000, namespace: swww
	Layer level 1 (bottom):
	Layer level 2 (top):
		Layer 56c8bca95ce0: xywh: 0 0 10 10, namespace: waycorner
		Layer 56c8bc9d4f70: xywh: 1490 0 10 10, namespace: waycorner
		Layer 56c8bca55650: xywh: 1490 990 10 10, namespace: waycorner
		Layer 56c8bdf55e00: xywh: 0 990 10 10, namespace: waycorner
		Layer 56c8bbc784b0: xywh: 0 0 1500 28, namespace: waybar
	Layer level 3 (overlay):

```

Thanks again for this great project

**Comment by AndreasBackx** [comment] 2024-03-20 11:03
Hmmm, that does seem like an issue. We should perhaps use the overlay layer instead of the top layer here: https://github.com/AndreasBackx/waycorner/blob/main/src/wayland.rs#L251. I guess this should be fine, my original worry was interference with a lock screen though if the same logic can be applied, then that should always be on top of waycorner.

**Comment by kRHYME7** [comment] 2024-03-20 12:42
Hey, thank you for the attention. I'll be happy to test this.

**Comment by AndreasBackx** [comment] 2024-03-20 19:58
@kRHYME7 if you could put up a diff to change the layer to overlay, test it by compiling, and confirm the issue is resolved, then I'd be happy to merge and make a new version.

Could you additionally do me another favour and test whether `swaylock` or another locking application then still is on top of waycorner? You can test this by running with `--preview` and see that it's not on top of the overlay.

**Comment by kRHYME7** [comment] 2024-03-21 02:14
> Could you additionally do me another favour and test whether swaylock or another locking application then still is on top of waycorner? You can test this by running with --preview and see that it's not on top of the overlay.

Sure!

I've tested it. It is same level as the notification layer

```
❯ sleep 3 && hyprctl layers
Monitor eDP-1:
	Layer level 0 (background):
		Layer 5b8885c1d700: xywh: 0 0 1500 1000, namespace: swww
	Layer level 1 (bottom):
	Layer level 2 (top):
		Layer 5b8885bf2650: xywh: 0 100 1 800, namespace: waycorner
		Layer 5b8885bf3640: xywh: 1495 995 5 5, namespace: waycorner
		Layer 5b8885bf44b0: xywh: 1499 100 1 800, namespace: waycorner
		Layer 5b888619b180: xywh: 0 0 1500 28, namespace: waybar
	Layer level 3 (overlay):
		Layer 5b8886180830: xywh: 1499 100 1 800, namespace: waycorner
		Layer 5b8886183940: xywh: 0 100 1 800, namespace: waycorner
		Layer 5b88861784e0: xywh: 1490 0 10 10, namespace: waycorner
		Layer 5b88861962e0: xywh: 20 0 1460 100, namespace: waycorner
		Layer 5b8886192aa0: xywh: 0 0 10 10, namespace: waycorner
		Layer 5b888618e140: xywh: 1495 995 5 5, namespace: waycorner
		Layer 5b8885cd5fd0: xywh: 1171 48 309 305, namespace: notifications
		Layer 5b8886189a40: xywh: 535 28 300 534, namespace: rofi
```


Should I issue a PR? What other instance should I test it 

✔️ Same level as the notification
✔️ Does not conflict with swaylock & hyprlock (wayland protocol )

**Comment by AndreasBackx** [comment] 2024-03-21 12:33
Thank you! Will issue a new release this evening after work.

**Comment by AndreasBackx** [comment] 2024-03-21 23:36
Released, thanks again!

**Closed as completed by AndreasBackx** 2024-03-21 23:36 UTC
